import { CarProps } from "@/globals";
import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";

const SLSModel: React.FC<CarProps> = (props) => {
  const { nodes, materials } = useGLTF("/assets/sls/sls.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.941, -0.015, -2.259]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0.geometry}
          material={materials.SL63_darkred}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_1.geometry}
          material={materials.SL63_silver}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_2.geometry}
          material={materials.SL63_brakelight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_3.geometry}
          material={materials.SL63_plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_4.geometry}
          material={materials.SL63_reverselight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_5.geometry}
          material={materials["SL63_runninglight-R"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_6.geometry}
          material={materials["SL63_beams-R"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_7.geometry}
          material={materials.SL63_signal_L_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_8.geometry}
          material={materials.SL63_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_9.geometry}
          material={materials.SL63_carbon}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_10.geometry}
          material={materials["SL63_black-leather"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_11.geometry}
          material={materials.SL63_steerSymbs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_12.geometry}
          material={materials["SL63_white-leather"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_13.geometry}
          material={materials.SL63_interiorSymbs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_14.geometry}
          material={materials.SL63_stitching}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_15.geometry}
          material={materials["SL63_ambiente-on"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_16.geometry}
          material={materials["seat.5"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_17.geometry}
          material={props.materials.body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_18.geometry}
          material={materials.SL63_mirror}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_19.geometry}
          material={materials.SL63_signal_L}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_20.geometry}
          material={materials.SL63_gauges_screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_21.geometry}
          material={materials["door_lf_ok.9"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_22.geometry}
          material={materials["body.6"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_23.geometry}
          material={materials.SL63_speakers}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_24.geometry}
          material={materials.SL63_carpet}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_25.geometry}
          material={materials.SL63_underbody}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_26.geometry}
          material={materials.SL63_underbody}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_27.geometry}
          material={materials["wheel.3"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_28.geometry}
          material={materials.SL63_dark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_29.geometry}
          material={materials.shiftlight_multi}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_30.geometry}
          material={materials["SL63_GPS-Screen"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_31.geometry}
          material={materials.bastion_mechanical}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_32.geometry}
          material={materials.bastion_mechanical}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_33.geometry}
          material={materials.SL63_b}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_34.geometry}
          material={materials["chassis.2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_35.geometry}
          material={materials["chassis.7"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_36.geometry}
          material={materials["chassis.8"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_37.geometry}
          material={materials["chassis.14"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_38.geometry}
          material={materials["engine.12"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_39.geometry}
          material={materials["engine.15"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_40.geometry}
          material={materials.SL63_radiatorsupp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_41.geometry}
          material={materials["SL63_black.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_42.geometry}
          material={materials["SL63_runninglight-Fr"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_43.geometry}
          material={materials["SL63_lowbeams-F.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_44.geometry}
          material={materials["SL63_runninglight-Fl"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_45.geometry}
          material={materials["SL63_tinted-glass"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_46.geometry}
          material={materials["SL63_tinted-glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_47.geometry}
          material={materials["Scene_-_Root.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_48.geometry}
          material={materials["amdb11_brake.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_49.geometry}
          material={materials["amdb11_misc_chrome.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_50.geometry}
          material={materials["amdb11_misc.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_51.geometry}
          material={materials["amdb11_badging.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_52.geometry}
          material={materials["amdb11_caliper.002"]}
        />
      </group>
    </group>
  );
}

export default SLSModel;

useGLTF.preload("/assets/sls/sls.glb");
