// @ts-nocheck

import type { CarProps } from "@/globals";
import { useGLTF } from "@react-three/drei";
import { useRef } from "react";
import type { Mesh } from "three";

const ViperModel: React.FC<CarProps> = (props) => {
	const { nodes, materials } = useGLTF("/assets/viper/viper.glb");
	const bodyRef = useRef<Mesh>(null);

	return (
		<group {...props} dispose={null}>
			<group position={[-1.204, 0, -2.759]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0.geometry}
					material={materials["black.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_1.geometry}
					material={materials["black_matt.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_2.geometry}
					material={props.materials.calipers}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_3.geometry}
					material={props.materials.rims}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_4.geometry}
					material={materials["black_matt.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_5.geometry}
					material={props.materials.body}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_6.geometry}
					material={materials["brakes2.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_7.geometry}
					material={materials["chrome.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_8.geometry}
					material={materials["chrome_d.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_9.geometry}
					material={materials["d_glass.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_10.geometry}
					material={materials["d_red.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_11.geometry}
					material={materials["glass.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_12.geometry}
					material={materials["gold.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_13.geometry}
					material={materials["grid.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_14.geometry}
					material={props.materials.interiorAccent}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_15.geometry}
					material={materials["interior_blue.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_16.geometry}
					material={materials["interior_bump.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_17.geometry}
					material={materials["interior_carbon.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_18.geometry}
					material={props.materials.interiorBase}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_19.geometry}
					material={materials["interior_decals.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_20.geometry}
					material={materials["interior_red.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_21.geometry}
					material={materials["interior_silver.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_22.geometry}
					material={materials["interior_speakers.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_23.geometry}
					material={materials["lights.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_24.geometry}
					material={materials["logo.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_25.geometry}
					material={materials["plate.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_26.geometry}
					material={materials["r_glass.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_27.geometry}
					material={materials["r_lights.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_28.geometry}
					material={materials["silver_d.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.mesh_0_29.geometry}
					material={materials["tire_mat5.001"]}
				/>
			</group>
		</group>
	);
};

export default ViperModel;

useGLTF.preload("/assets/viper/viper.glb");
